/* 
     * BranchesAdminFrom
     * Created on 03-11-2015
     * Copyright(c) 2015 PericosCorp Company, Inc.  All Rights Reserved.
     * This software is the proprietary information of PericosCorp Company.
 */
package pericoscorp.inventorymanager.desktop.gui.admin.Products;
import PericosCorp.InventoryManager.Domain.Entities.MeasurementUnit;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IMeasurementUnitRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pericoscorp.inventorymanager.desktop.gui.InternalCenterFrame;

/**
 *
 * @author Arturo E. Salinas
 */
public class MeasurementUnitAdminFrom extends InternalCenterFrame {
    private IMeasurementUnitRepository mur;
    DefaultTableModel dtm;
    private boolean  isEditing=false;
    /**
     * Creates new form AdminRolesForm
     */
    public MeasurementUnitAdminFrom() {
        initComponents();
        mur= (IMeasurementUnitRepository)ctx.getBean("IMeasurementUnitRepository");
        dtm = new DefaultTableModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Abreviación");            
        dtm.addColumn("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_units = new javax.swing.JTable();
        panelAddUnits = new javax.swing.JPanel();
        lb_newRole = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_description = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_unitName = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        txt_unitAbbreviation = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        panelButtons = new javax.swing.JPanel();
        btn_edit = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Admin Unidades de Medida");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(600, 800));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelRoles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbl_units.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_units.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_unitsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_units);

        javax.swing.GroupLayout panelRolesLayout = new javax.swing.GroupLayout(panelRoles);
        panelRoles.setLayout(panelRolesLayout);
        panelRolesLayout.setHorizontalGroup(
            panelRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRolesLayout.setVerticalGroup(
            panelRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAddUnits.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelAddUnits.setEnabled(false);

        lb_newRole.setText("Agegar/modificar Unidades");

        lb_name.setText("* Nombre:");

        lb_description.setText("* Abreviación:");

        btn_add.setText("Guardar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_clear.setText("Limpiar");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        txt_id.setEditable(false);

        txt_unitName.setIsRequired(true);
        txt_unitName.setLength(100);

        txt_unitAbbreviation.setIsRequired(true);
        txt_unitAbbreviation.setLength(10);

        javax.swing.GroupLayout panelAddUnitsLayout = new javax.swing.GroupLayout(panelAddUnits);
        panelAddUnits.setLayout(panelAddUnitsLayout);
        panelAddUnitsLayout.setHorizontalGroup(
            panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddUnitsLayout.createSequentialGroup()
                .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_newRole)
                    .addGroup(panelAddUnitsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_description)
                            .addComponent(lb_name)
                            .addGroup(panelAddUnitsLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddUnitsLayout.createSequentialGroup()
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_unitAbbreviation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txt_unitName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelAddUnitsLayout.setVerticalGroup(
            panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddUnitsLayout.createSequentialGroup()
                .addComponent(lb_newRole)
                .addGap(10, 10, 10)
                .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_name)
                    .addComponent(txt_unitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_description)
                    .addComponent(txt_unitAbbreviation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddUnitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_edit.setText("Modificar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelAddUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAddUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void fillTable(List<MeasurementUnit> units,DefaultTableModel model)    
    {        
        model.setRowCount(0);
        this.tbl_units.setModel(model);             
        this.tbl_units.getColumnModel().getColumn(2).setMinWidth(0);
        this.tbl_units.getColumnModel().getColumn(2).setMaxWidth(0);        
        Object [] fila = new Object[3];
        for(MeasurementUnit mu : units)
        {
           fila[0] = mu.getName();
           fila[1] = mu.getAbbreviation();           
           fila[2] = mu.getId();
           model.addRow(fila);
        }            
    }
     
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        fillTable(mur.GetAll(), dtm);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(!ValidRequiredFields(panelAddUnits))
            return;
        if(!isEditing)
        {
            int result= mur.CreateNewMeasurementUnit(this.txt_unitName.getText().trim(),this.txt_unitAbbreviation.getText().trim());
            if(result==1) 
            {
               JOptionPane.showMessageDialog(this.getContentPane(), "Unidad guardada satisfactoriamente");
               this.clearFields(btn_add.getParent());
               isEditing=false;
               fillTable(mur.GetAll(), dtm);
            }       
            else if(result==0)
                JOptionPane.showMessageDialog(this.getContentPane(), "Debe completar los campos obligatorios (*)");
            else
                JOptionPane.showMessageDialog(this.getContentPane(), "Error al guardar la unidad, porfavor intente de nuevo, si el problema persiste contactor al administrador del sistema");
        }
        else
        {
            int confirm=JOptionPane.showConfirmDialog(this.getContentPane(), "¿Seguro que desea modificar esta unidad?");
            if(confirm!=0)
                return;
            int result= mur.UpdateMeasurementUnit(Integer.parseInt(this.txt_id.getText()),this.txt_unitName.getText().trim(), this.txt_unitAbbreviation.getText().trim());
            if(result==1) 
            {
               JOptionPane.showMessageDialog(this.getContentPane(), "Unidad actualizada satisfactoriamente");
               this.clearFields(btn_add.getParent());
               isEditing=false;
               fillTable(mur.GetAll(), dtm);
            }       
            else if(result==0)
                JOptionPane.showMessageDialog(this.getContentPane(), "Debe completar los campos obligatorios (*)");
            else
                JOptionPane.showMessageDialog(this.getContentPane(), "Error al actualizar la unidad, porfavor intente de nuevo, si el problema persiste contactor al administrador del sistema");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        this.clearFields(btn_clear.getParent());
        isEditing=false;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
       if(tbl_units.getSelectedRow()!=-1)
       {
           fillUnittoEdit(tbl_units.getSelectedRow());
           isEditing=true;
           this.txt_unitName.requestFocus();
       }
       else
       {
           JOptionPane.showMessageDialog(this.getContentPane(), "Debe seleccionar la sucursal que desea modificar");
           isEditing=false;
       }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        isEditing=false;
        clearFields(panelAddUnits);
        this.txt_unitName.requestFocus();
    }//GEN-LAST:event_btn_newActionPerformed

    private void tbl_unitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_unitsMouseClicked
        clearFields(panelAddUnits);
    }//GEN-LAST:event_tbl_unitsMouseClicked
 
    private void fillUnittoEdit(int unitSelected)
    {        
        this.txt_unitName.setText(this.tbl_units.getValueAt(unitSelected, 0).toString());
        this.txt_unitAbbreviation.setText(this.tbl_units.getValueAt(unitSelected, 1).toString());        
        this.txt_id.setText(this.tbl_units.getValueAt(unitSelected, 2).toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_description;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_newRole;
    private javax.swing.JPanel panelAddUnits;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelRoles;
    private javax.swing.JTable tbl_units;
    private javax.swing.JTextField txt_id;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_unitAbbreviation;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_unitName;
    // End of variables declaration//GEN-END:variables
}
