/* 
     * BranchesAdminFrom
     * Created on 03-11-2015
     * Copyright(c) 2015 PericosCorp Company, Inc.  All Rights Reserved.
     * This software is the proprietary information of PericosCorp Company.
 */
package pericoscorp.inventorymanager.desktop.gui.admin.Products;
import PericosCorp.InventoryManager.Domain.Entities.MeasurementUnit;
import PericosCorp.InventoryManager.Domain.Entities.Product;
import PericosCorp.InventoryManager.Domain.Entities.ProductCategory;
import PericosCorp.InventoryManager.Domain.Entities.Provider;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IMeasurementUnitRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProductCategoryRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProductRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProviderRepository;
import PericosCorp.InventoryManager.Domain.Services.Interfaces.IProductService;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pericoscorp.inventorymanager.desktop.gui.InternalCenterFrame;

/**
 *
 * @author Arturo E. Salinas
 */
public class ProductAdminFrom extends InternalCenterFrame {
    private IProductRepository pr;
    private IProductCategoryRepository pcr;
    private IMeasurementUnitRepository measurementUnitRepository;
    private IProviderRepository providerRepository;
    private IProductService productService;
    private IProductRepository productRepository;
    DefaultTableModel dtm;
    DefaultComboBoxModel categories;
    DefaultComboBoxModel providers;
    DefaultComboBoxModel measurements;
    private boolean  isEditing=false;
    /**
     * Creates new form AdminRolesForm
     */
    public ProductAdminFrom() {
        initComponents();
        pr= (IProductRepository)ctx.getBean("IProductRepository");
        productService = (IProductService)ctx.getBean("IProductService");
        measurementUnitRepository=(IMeasurementUnitRepository)ctx.getBean("IMeasurementUnitRepository");
        providerRepository = (IProviderRepository)ctx.getBean("IProviderRepository");
        productRepository = (IProductRepository)ctx.getBean("IProductRepository");
        pcr = (IProductCategoryRepository)ctx.getBean("IProductCategoryRepository");
        dtm = new DefaultTableModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Categoria");  
        dtm.addColumn("Proveedor");          
        dtm.addColumn("");        
        categories = new DefaultComboBoxModel(pcr.GetAll().toArray());
        categories.insertElementAt(new ProductCategory("Seleccione una categoria",""), 0);        
        this.cmb_Categories.setModel(categories);
        this.cmb_Categories.setSelectedIndex(0);
        providers = new DefaultComboBoxModel(providerRepository.GetAll().toArray());
        providers.insertElementAt(new Provider("Seleccione un proveedor","","","",""), 0);        
        this.cmb_Providers.setModel(providers);
        this.cmb_Providers.setSelectedIndex(0);
        measurements = new DefaultComboBoxModel(measurementUnitRepository.GetAll().toArray());
        measurements.insertElementAt(new MeasurementUnit("Seleccione una unidad de medida",""), 0);
        this.cmb_Units.setModel(measurements);
        this.cmb_Units.setSelectedIndex(0);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Find = new javax.swing.JLabel();
        txt_find = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        panelRoles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();
        panelAddProduct = new javax.swing.JPanel();
        lb_newRole = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        lb_description = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lb_description1 = new javax.swing.JLabel();
        txt_productName = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        txt_productDescription = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        txt_productBrand = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        jLabel2 = new javax.swing.JLabel();
        txt_productModel = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        jLabel3 = new javax.swing.JLabel();
        cmb_Categories = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        jLabel4 = new javax.swing.JLabel();
        cmb_Providers = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        jLabel5 = new javax.swing.JLabel();
        cmb_Units = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        panelButtons = new javax.swing.JPanel();
        btn_edit = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Admin Sucursales");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(600, 800));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lb_Find.setText("Buscar producto:");
        lb_Find.setToolTipText("");

        btn_Search.setText("Buscar");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        panelRoles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_products);

        javax.swing.GroupLayout panelRolesLayout = new javax.swing.GroupLayout(panelRoles);
        panelRoles.setLayout(panelRolesLayout);
        panelRolesLayout.setHorizontalGroup(
            panelRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelRolesLayout.setVerticalGroup(
            panelRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRolesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAddProduct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelAddProduct.setEnabled(false);

        lb_newRole.setText("Agegar/modificar Productos");

        lb_name.setText("* Nombre:");

        lb_description.setText("   Descripción:");

        btn_add.setText("Guardar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_clear.setText("Limpiar");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        txt_id.setEditable(false);

        lb_description1.setText("   Marca:");

        txt_productName.setIsRequired(true);
        txt_productName.setLength(200);

        txt_productDescription.setLength(100);

        txt_productBrand.setLength(150);

        jLabel2.setText("   Modelo:");

        txt_productModel.setLength(100);

        jLabel3.setText("* Categoria:");

        cmb_Categories.setIsRequired(true);

        jLabel4.setText("* Proveedor:");

        cmb_Providers.setIsRequired(true);

        jLabel5.setText("* Unidad de Medida:");

        javax.swing.GroupLayout panelAddProductLayout = new javax.swing.GroupLayout(panelAddProduct);
        panelAddProduct.setLayout(panelAddProductLayout);
        panelAddProductLayout.setHorizontalGroup(
            panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductLayout.createSequentialGroup()
                .addComponent(lb_newRole)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAddProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_description)
                    .addComponent(lb_name)
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addComponent(lb_description1))
                .addGap(18, 18, 18)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAddProductLayout.createSequentialGroup()
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_productDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txt_productName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_productModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Categories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Providers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cmb_Units, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        panelAddProductLayout.setVerticalGroup(
            panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProductLayout.createSequentialGroup()
                .addComponent(lb_newRole)
                .addGap(10, 10, 10)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_productModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_name)
                    .addComponent(txt_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_description)
                    .addComponent(txt_productDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_Providers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_description1)
                    .addComponent(txt_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_Units, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_clear))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_edit.setText("Modificar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Find)
                                .addGap(10, 10, 10)
                                .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(315, 315, 315)
                                .addComponent(btn_Search)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lb_Find))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Search))
                .addGap(18, 18, 18)
                .addComponent(panelRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void fillTable(List<Product> products,DefaultTableModel model)    
    {        
        model.setRowCount(0);
        this.tbl_products.setModel(model);             
        this.tbl_products.getColumnModel().getColumn(3).setMinWidth(0);
        this.tbl_products.getColumnModel().getColumn(3).setMaxWidth(0);        
        Object [] fila = new Object[4];
        for(Product p:products)
        {
           fila[0]=p.getName();
           fila[1]=p.getProductCategory().getName();
           fila[2]=p.getProvider().getName();
           fila[3]=p.getId();
           model.addRow(fila);
        }            
    }
     
     private int GetCategoryIdSelected()
     {
         ProductCategory pc =(ProductCategory) this.categories.getElementAt(this.cmb_Categories.getSelectedIndex());
         return pc.getId();
     }
     
     private int GetProviderIdSelected()
     {
         Provider p = (Provider)this.providers.getElementAt(this.cmb_Providers.getSelectedIndex());
         return p.getId();
     }
     
     private int GetMeasurementUnitIdSelected()
     {
         MeasurementUnit mu = (MeasurementUnit)this.measurements.getElementAt(this.cmb_Units.getSelectedIndex());
         return mu.getId();
     }
     
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        fillTable(pr.GetAll(), dtm);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(!ValidRequiredFields(panelAddProduct))
            return;
        if(!isEditing)
        {
            int result= productService.CreateNewProduct(GetCategoryIdSelected(), GetProviderIdSelected(), GetMeasurementUnitIdSelected(),
                    this.txt_productName.getText().trim()
                    ,this.txt_productDescription.getText().trim(),this.txt_productBrand.getText().trim(), this.txt_productModel.getText().trim());
            if(result==1) 
            {
               JOptionPane.showMessageDialog(this.getContentPane(), "Producto guardado satisfactoriamente");
               this.clearFields(btn_add.getParent());
               isEditing=false;
               fillTable(pr.GetAll(), dtm);
            }       
            else if(result==0)
                JOptionPane.showMessageDialog(this.getContentPane(), "Debe completar los campos obligatorios (*)");
            else
                JOptionPane.showMessageDialog(this.getContentPane(), "Error al guardar el producto, porfavor intente de nuevo, si el problema persiste contactor al administrador del sistema");
        }
//        else
//        {
//            int confirm=JOptionPane.showConfirmDialog(this.getContentPane(), "¿Seguro que desea modificar esta sucursal?");
//            if(confirm!=0)
//                return;
//            int result= pr.UpdateBranch(Integer.parseInt(this.txt_id.getText()),this.txt_branchName.getText().trim(),this.txt_branchAddress.getText().trim(),this.txt_branchPhone.getText());
//            if(result==1) 
//            {
//               JOptionPane.showMessageDialog(this.getContentPane(), "Sucursal actualizada satisfactoriamente");
//               this.clearFields(btn_add.getParent());
//               isEditing=false;
//               fillTable(pr.GetAll(), dtm);
//            }       
//            else if(result==0)
//                JOptionPane.showMessageDialog(this.getContentPane(), "Debe completar los campos obligatorios (*)");
//            else
//                JOptionPane.showMessageDialog(this.getContentPane(), "Error al actualizar la sucursal, porfavor intente de nuevo, si el problema persiste contactor al administrador del sistema");
//        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        this.clearFields(btn_clear.getParent());
        isEditing=false;
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
//        fillTable(pr.FilterByName(this.txt_find.getText()), dtm);
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
       if(tbl_products.getSelectedRow()!=-1)
       {
           fillProducttoEdit(tbl_products.getSelectedRow());
           isEditing=true;
           this.txt_productName.requestFocus();
       }
       else
       {
           JOptionPane.showMessageDialog(this.getContentPane(), "Debe seleccionar el producto que desea modificar");
           isEditing=false;
       }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        isEditing=false;
        clearFields(panelAddProduct);
        this.txt_productName.requestFocus();
    }//GEN-LAST:event_btn_newActionPerformed

    private void tbl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productsMouseClicked
        clearFields(panelAddProduct);
    }//GEN-LAST:event_tbl_productsMouseClicked

    private boolean isSelectedRow()
    {
        return tbl_products.getSelectedRow()!=-1;
    }
    
    private int getSelectedRow()
    {
        return tbl_products.getSelectedRow();
    }
    
    private void fillProducttoEdit(int productSelected)
    {        
        if(this.tbl_products.getSelectedRow()!=-1)
        {
            Product p = productRepository.Get(Integer.parseInt(this.tbl_products.getValueAt(productSelected, 3).toString()));
            this.txt_productName.setText(p.getName());
            this.txt_id.setText(String.valueOf(p.getId()));
            this.txt_productBrand.setText(p.getBrand());
            this.txt_productDescription.setText(p.getDescription());
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_new;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_Categories;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_Providers;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_Units;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Find;
    private javax.swing.JLabel lb_description;
    private javax.swing.JLabel lb_description1;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_newRole;
    private javax.swing.JPanel panelAddProduct;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelRoles;
    private javax.swing.JTable tbl_products;
    private javax.swing.JTextField txt_find;
    private javax.swing.JTextField txt_id;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_productBrand;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_productDescription;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_productModel;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_productName;
    // End of variables declaration//GEN-END:variables
}
