/* 
 * Principal
 * Created on 03-11-2015
 * Copyright(c) 2015 PericosCorp Company, Inc.  All Rights Reserved.
 * This software is the proprietary information of PericosCorp Company.
 */
package pericoscorp.inventorymanager.desktop.gui;

import javax.swing.UIManager;
import org.pushingpixels.substance.api.skin.SubstanceBusinessBlueSteelLookAndFeel;
import org.pushingpixels.substance.api.skin.SubstanceGraphiteLookAndFeel;
import pericoscorp.inventorymanager.desktop.gui.Products.CategoriesAdminFrom;
import pericoscorp.inventorymanager.desktop.gui.admin.branches.BranchesAdminFrom;
import pericoscorp.inventorymanager.desktop.gui.admin.employees.EmployeesAdminFrom;
import pericoscorp.inventorymanager.desktop.gui.admin.roles.AdminRolesForm;

/**
 *
 * @author Arturo E. Salinas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {        
        initComponents();
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        AdminMenu = new javax.swing.JMenu();
        RolesMenu = new javax.swing.JMenuItem();
        BranchesMenu = new javax.swing.JMenuItem();
        employeesMenu = new javax.swing.JMenuItem();
        menu_Products = new javax.swing.JMenu();
        menu_Categories = new javax.swing.JMenuItem();
        menu_ProductsSubMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 800));

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        AdminMenu.setMnemonic('f');
        AdminMenu.setText("Administración");

        RolesMenu.setMnemonic('o');
        RolesMenu.setText("Roles");
        RolesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolesMenuActionPerformed(evt);
            }
        });
        AdminMenu.add(RolesMenu);

        BranchesMenu.setText("Sucursales");
        BranchesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchesMenuActionPerformed(evt);
            }
        });
        AdminMenu.add(BranchesMenu);

        employeesMenu.setText("Empleados");
        employeesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesMenuActionPerformed(evt);
            }
        });
        AdminMenu.add(employeesMenu);

        menu_Products.setText("Productos");

        menu_Categories.setText("Categorias");
        menu_Categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CategoriesActionPerformed(evt);
            }
        });
        menu_Products.add(menu_Categories);

        menu_ProductsSubMenu.setText("Productos");
        menu_Products.add(menu_ProductsSubMenu);

        AdminMenu.add(menu_Products);

        menuBar.add(AdminMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RolesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolesMenuActionPerformed
        AdminRolesForm arf = new AdminRolesForm();
        this.desktopPane.add(arf);
        arf.show();
    }//GEN-LAST:event_RolesMenuActionPerformed

    private void BranchesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchesMenuActionPerformed
        BranchesAdminFrom baf = new BranchesAdminFrom();
        this.desktopPane.add(baf);
        baf.show();
    }//GEN-LAST:event_BranchesMenuActionPerformed

    private void employeesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesMenuActionPerformed
        EmployeesAdminFrom eaf = new EmployeesAdminFrom();
        this.desktopPane.add(eaf);
        eaf.show();
    }//GEN-LAST:event_employeesMenuActionPerformed

    private void menu_CategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CategoriesActionPerformed
        CategoriesAdminFrom caf = new CategoriesAdminFrom();
        this.desktopPane.add(caf);
        caf.show();
    }//GEN-LAST:event_menu_CategoriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new SubstanceBusinessBlueSteelLookAndFeel());
                } catch (Exception e) {
                    System.out.println("Substance Graphite failed to initialize");
                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem BranchesMenu;
    private javax.swing.JMenuItem RolesMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem employeesMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_Categories;
    private javax.swing.JMenu menu_Products;
    private javax.swing.JMenuItem menu_ProductsSubMenu;
    // End of variables declaration//GEN-END:variables

}
