/* 
     * AdminRolesForm
     * Created on 03-11-2015
     * Copyright(c) 2015 PericosCorp Company, Inc.  All Rights Reserved.
     * This software is the proprietary information of PericosCorp Company.
 */
package pericoscorp.inventorymanager.desktop.gui.Registers;

import PericosCorp.InventoryManager.Domain.Dtos.MovementDetailDto;
import PericosCorp.InventoryManager.Domain.Dtos.ProductDto;
import PericosCorp.InventoryManager.Domain.Entities.Provider;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProductRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProviderRepository;
import PericosCorp.InventoryManager.Domain.Services.Interfaces.IMovementService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pericoscorp.inventorymanager.desktop.gui.InternalCenterFrame;

/**
 *
 * @author Arturo E. Salinas
 */
public class InMovementsForm extends InternalCenterFrame {
    private final IProductRepository productRepository;
    private final IProviderRepository providerRepository;
    private final IMovementService movementService;
    
    private int SelectedRowOnTable=0;
    private final DefaultTableModel buyDetails;
    private boolean  isEditing=false;
    private final DefaultComboBoxModel providers;
    private DefaultComboBoxModel products;
    private List<MovementDetailDto>details;
    /**
     * Creates new form AdminRolesForm
     */
    public InMovementsForm() {
        initComponents();
        productRepository= (IProductRepository)ctx.getBean("IProductRepository");
        providerRepository =(IProviderRepository)ctx.getBean("IProviderRepository");   
        movementService=(IMovementService)ctx.getBean("IMovementService");
        providers=new DefaultComboBoxModel(providerRepository.GetAll().toArray());
        providers.insertElementAt(new Provider("Seleccione un proveedor", "", "", "", "",""), 0);
        cmb_providers.setModel(providers);
        cmb_providers.setSelectedIndex(0);
        buyDetails = new DefaultTableModel();
        buyDetails.addColumn("Producto");
        buyDetails.addColumn("Precio");  
        buyDetails.addColumn("Cantidad");  
        buyDetails.addColumn("");        
        this.tbl_details.setModel(buyDetails);
        this.tbl_details.getColumnModel().getColumn(3).setMinWidth(0);
        this.tbl_details.getColumnModel().getColumn(3).setMaxWidth(0);  
        details= new ArrayList<MovementDetailDto>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuy = new javax.swing.JPanel();
        lb_name = new javax.swing.JLabel();
        lb_description = new javax.swing.JLabel();
        txt_numRef = new pericoscorp.swingcustomcontrolls.BaseTextBoxValidated();
        txt_date = new pericoscorp.swingcustomcontrolls.DateTextBox();
        jLabel2 = new javax.swing.JLabel();
        cmb_providers = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_details = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmb_products = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        jLabel4 = new javax.swing.JLabel();
        txt_quantity = new pericoscorp.swingcustomcontrolls.NumericTextBox();
        jLabel5 = new javax.swing.JLabel();
        txt_price = new pericoscorp.swingcustomcontrolls.NumericTextBox();
        btn_addDetail = new javax.swing.JButton();
        btn_removeDetail = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro de Compras");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(600, 800));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panelBuy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelBuy.setEnabled(false);

        lb_name.setText("* Fecha (dd/MM/yyyy):");

        lb_description.setText("* No.  Factura:");

        txt_numRef.setIsRequired(true);
        txt_numRef.setLength(100);

        txt_date.setIsRequired(true);

        jLabel2.setText("* Proveedor:");

        cmb_providers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_providersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuyLayout = new javax.swing.GroupLayout(panelBuy);
        panelBuy.setLayout(panelBuyLayout);
        panelBuyLayout.setHorizontalGroup(
            panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_description)
                    .addComponent(lb_name)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_numRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_providers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBuyLayout.setVerticalGroup(
            panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_name)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_description)
                    .addComponent(txt_numRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_providers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbl_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_detailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_details);

        jLabel1.setText("Detalles de ingreso:");

        detailPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setText("* Producto:");

        cmb_products.setIsRequired(true);

        jLabel4.setText("* Cantidad:");

        txt_quantity.setIsRequired(true);

        jLabel5.setText("* Precio:");

        txt_price.setIsRequired(true);

        btn_addDetail.setText("Agregar detalle");
        btn_addDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addDetailActionPerformed(evt);
            }
        });

        btn_removeDetail.setText("Eliminar detalle");
        btn_removeDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeDetailActionPerformed(evt);
            }
        });

        btn_edit.setText("Modificar detalle");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_products, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(detailPanelLayout.createSequentialGroup()
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGap(43, 43, 43)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_addDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_removeDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addDetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_removeDetail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_edit)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btn_save.setText("Guardar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_clear.setText("Limpiar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_save)
                .addGap(33, 33, 33)
                .addComponent(btn_clear)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(panelBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void GetProductsByProvider()
    {
        int providerId= ((Provider)providers.getElementAt(cmb_providers.getSelectedIndex())).getId();
        products = new DefaultComboBoxModel(productRepository.FilterByProvider(providerId).toArray());
        products.insertElementAt(new ProductDto("Seleccione un producto"), 0);
        cmb_products.setModel(products);
        cmb_products.setSelectedIndex(0);
    }
    
    private int GetProductIdSelected()
    {
        return ((ProductDto)this.products.getElementAt(this.cmb_products.getSelectedIndex())).getId();
    }
    
    private int GetProviderIdSelected()
    {
        return ((Provider)this.providers.getElementAt(this.cmb_providers.getSelectedIndex())).getId();
    }
    
    private String GetProductNameSelected()
    {
      return ((ProductDto)this.products.getElementAt(this.cmb_products.getSelectedIndex())).getName();
    }
    
    private void AddDetail()
    {
        for(MovementDetailDto detail:details)
        {
            if(detail.getProductId() == GetProductIdSelected())
            {
                JOptionPane.showMessageDialog(panelBuy, "Ya se ha agregado este producto, favor revisar");
                return;                
            }
        }
        MovementDetailDto detail = new MovementDetailDto();
        detail.setPrice(Double.parseDouble(this.txt_price.getText().trim()));
        detail.setProductId(GetProductIdSelected());
        detail.setQuantity(Double.parseDouble(this.txt_quantity.getText().trim()));
        details.add(detail);
        Object [] fila = new Object[4];
        fila[0] = GetProductNameSelected();
        fila[1] = detail.getPrice();
        fila[2] = detail.getQuantity();
        fila[3]=0;
        buyDetails.addRow(fila);
    }
    
    private void AddDetailEdited()
    {        
        MovementDetailDto detail = (MovementDetailDto)details.get(this.tbl_details.getSelectedRow());
        details.remove(detail);
        detail.setPrice(Double.parseDouble(this.txt_price.getText().trim()));
        detail.setProductId(GetProductIdSelected());
        detail.setQuantity(Double.parseDouble(this.txt_quantity.getText().trim()));        
        details.add(detail);
        buyDetails.removeRow(this.tbl_details.getSelectedRow());
        Object [] fila = new Object[4];
        fila[0] = GetProductNameSelected();
        fila[1] = detail.getPrice();
        fila[2] = detail.getQuantity();
        fila[3]=0;
        buyDetails.addRow(fila);
    }
 
    private void FillDetailToEdit()
    {
        if(this.tbl_details.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el detalle a modificar");
        }
        else
        {
            MovementDetailDto detail =(MovementDetailDto)details.get(this.tbl_details.getSelectedRow());
            this.txt_price.setText(String.valueOf(detail.getPrice()));
            this.txt_quantity.setText(String.valueOf(detail.getQuantity()));            
            for(int i=0;i<products.getSize();i++)
            {
                if(((ProductDto)products.getElementAt(i)).getId()==detail.getProductId())
                {
                    this.cmb_products.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
     
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btn_addDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addDetailActionPerformed
        if(isEditing)
        {
            AddDetailEdited();
            clearFields(detailPanel);        
        }
        else
        {
            AddDetail();
            clearFields(detailPanel);        
        }
        
    }//GEN-LAST:event_btn_addDetailActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(ValidRequiredFields(panelBuy))
        {
            if(details.isEmpty())
                JOptionPane.showMessageDialog(rootPane,"Debe introducir el detalle de la compra.");
            int res = movementService.SaveMovement(ConvertToDate(this.txt_date.getText()), this.txt_numRef.getText().trim(),GetProviderIdSelected(),0, details);
            if(res==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Entrada guardada satisfactoriamente");
                clearFields(panelBuy);
                clearFields(detailPanel);
                buyDetails.setRowCount(0);
            }
            else if(res==0)
                JOptionPane.showMessageDialog(rootPane,"Debe completar los campos obligatorios (*)");                
            else 
                JOptionPane.showMessageDialog(rootPane, "Ocurrio un error mientras se guardaba la entrada, favor reintente o contactar al administrador del sistema");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void cmb_providersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_providersActionPerformed
        GetProductsByProvider();
    }//GEN-LAST:event_cmb_providersActionPerformed

    private void btn_removeDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeDetailActionPerformed
        details.remove(this.tbl_details.getSelectedRow());
        buyDetails.removeRow(this.tbl_details.getSelectedRow());
        System.out.println(details.size());
        
    }//GEN-LAST:event_btn_removeDetailActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        FillDetailToEdit();
        isEditing=true;
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_detailsMouseClicked
        if(this.tbl_details.getSelectedRow()!= SelectedRowOnTable)
        {
            SelectedRowOnTable=this.tbl_details.getSelectedRow();
            clearFields(detailPanel);
            isEditing=false;
        }
    }//GEN-LAST:event_tbl_detailsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addDetail;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_removeDetail;
    private javax.swing.JButton btn_save;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_products;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_providers;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_description;
    private javax.swing.JLabel lb_name;
    private javax.swing.JPanel panelBuy;
    private javax.swing.JTable tbl_details;
    private pericoscorp.swingcustomcontrolls.DateTextBox txt_date;
    private pericoscorp.swingcustomcontrolls.BaseTextBoxValidated txt_numRef;
    private pericoscorp.swingcustomcontrolls.NumericTextBox txt_price;
    private pericoscorp.swingcustomcontrolls.NumericTextBox txt_quantity;
    // End of variables declaration//GEN-END:variables
}
