/*
 * KardexForm
 * Created on 04-12-2015
 * Copyright(c) 2015 PericosCorp Company, Inc.  All Rights Reserved.
 * This software is the proprietary information of PericosCorp Company.
 */
package pericoscorp.inventorymanager.desktop.gui.Registers;

import PericosCorp.Framework.Core.StringsHelpers;
import PericosCorp.InventoryManager.Domain.Dtos.MovementDetailDto;
import PericosCorp.InventoryManager.Domain.Entities.InitialInventory;
import PericosCorp.InventoryManager.Domain.Entities.Product;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IInitialInventoryRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IMovementRepository;
import PericosCorp.InventoryManager.Domain.Repositories.Interfaces.IProductRepository;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import pericoscorp.inventorymanager.desktop.gui.InternalCenterFrame;

/**
 *
 * @author Arturo E. Salinas
 */
public class KardexForm extends InternalCenterFrame {

    /**
     * Creates new form KardexForm
     */
    private IMovementRepository movementRepository;
    private IProductRepository productRepository;
    private IInitialInventoryRepository initialInventoryRepository;
    private DefaultTableModel model;
    private DefaultComboBoxModel products;

    public KardexForm() {
        initComponents();
        movementRepository = (IMovementRepository) ctx.getBean("IMovementRepository");
        productRepository = (IProductRepository) ctx.getBean("IProductRepository");
        initialInventoryRepository = (IInitialInventoryRepository)ctx.getBean("IInitialInventoryRepository");
        products=new DefaultComboBoxModel(productRepository.GetAll().toArray());
        products.insertElementAt(new Product("Seleccion un producto"), 0);
        this.cmb_products.setModel(products);
        this.cmb_products.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_products = new pericoscorp.swingcustomcontrolls.BaseComboBoxValidated();
        jLabel1 = new javax.swing.JLabel();
        btn_generate = new javax.swing.JButton();
        panel_kardex = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_movements = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Producto:");

        btn_generate.setText("Generar Kardex");
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });

        panel_kardex.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tbl_movements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_movements);

        javax.swing.GroupLayout panel_kardexLayout = new javax.swing.GroupLayout(panel_kardex);
        panel_kardex.setLayout(panel_kardexLayout);
        panel_kardexLayout.setHorizontalGroup(
            panel_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kardexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_kardexLayout.setVerticalGroup(
            panel_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kardexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmb_products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_generate)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_kardex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_generate))
                .addGap(18, 18, 18)
                .addComponent(panel_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed
        List<MovementDetailDto> movements = movementRepository.GetMovementsByProductAndYear(GetSelectedProduct(), Calendar.getInstance().get(Calendar.YEAR));
        System.out.println(movements.size());
        fillTable(movements);
    }//GEN-LAST:event_btn_generateActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private int GetSelectedProduct()
    {
        Product p = (Product)products.getElementAt(this.cmb_products.getSelectedIndex());
        return p.getId();
    }
    private void fillTable(List<MovementDetailDto> movements) {
        model = new DefaultTableModel();
        model.addColumn("Fecha");
        model.addColumn("Movimiento");
        model.addColumn("Cantidad");
        model.addColumn("Precio Unitario");
        InitialInventory initialInventory = initialInventoryRepository.FindByProductAndYear(GetSelectedProduct(), Calendar.getInstance().get(Calendar.YEAR));
        Object[] row = new Object[4];
        if(initialInventory!=null)
        {        
            row[0] =StringsHelpers.GetStringofDate(initialInventory.getCreationDate());
            row[1] = "Inventario Inicial";
            row[2] = initialInventory.getStock();
            row[3] = initialInventory.getPriceCost();
            model.addRow(row);
            for (MovementDetailDto md : movements) {
                if(md.getProductId() == GetSelectedProduct() && md.getMovementId() != initialInventory.getMovement_Id() )
                {
                    row = new Object[4];
                    row[0] = StringsHelpers.GetStringofDate(md.getOperationDate());
                    row[1] = md.getMovementType() == 1 ? "Venta" : "Compra";
                    row[2] = md.getQuantity();
                    row[3] = md.getPrice();
                    model.addRow(row);
                }
            }
        }        
        Product p= productRepository.Get(GetSelectedProduct());
        row = new Object[4];
        row[0] = StringsHelpers.GetStringofDate(new Date());
        row[1] = "Saldo";
        row[2] = p.getStock();
        row[3] = p.getPriceCost();
        model.addRow(row);
        this.tbl_movements.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generate;
    private pericoscorp.swingcustomcontrolls.BaseComboBoxValidated cmb_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_kardex;
    private javax.swing.JTable tbl_movements;
    // End of variables declaration//GEN-END:variables
}
